export const PEER_LIST_REQUEST = 'PEER_LIST_REQUEST'
export const PEER_LIST_SUCCESS = 'PEER_LIST_SUCCESS'
export const PEER_LIST_ERROR = 'PEER_LIST_ERROR'

export const NETWORK_STATS_REQUEST = 'NETWORK_STATS_REQUEST'
export const NETWORK_STATS_SUCCESS = 'NETWORK_STATS_SUCCESS'
export const NETWORK_STATS_ERROR = 'NETWORK_STATS_ERROR'

export const NETWORK_MEMPOOL_REQUEST = 'NETWORK_MEMPOOL_REQUEST'
export const NETWORK_MEMPOOL_SUCCESS = 'NETWORK_MEMPOOL_SUCCESS'
export const NETWORK_MEMPOOL_ERROR = 'NETWORK_MEMPOOL_ERROR'
export const MEMPOOL_ADD_TRANSACTION = 'MEMPOOL_ADD_TRANSACTION'
export const MEMPOOL_CLEAR = 'MEMPOOL_CLEAR'