export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_ERROR = 'USER_ERROR'


export const SESSION_LIST_REQUEST = 'SESSION_LIST_REQUEST'
export const SESSION_LIST_REQUEST_SUCCESS = 'SESSION_LIST_REQUEST_SUCCESS'
export const SESSION_LIST_REQUEST_ERROR = 'SESSION_LIST_REQUEST_ERROR'