export const WALLET_LIST_REQUEST = 'WALLET_LIST_REQUEST'
export const WALLET_LIST_SUCCESS = 'WALLET_LIST_SUCCESS'
export const WALLET_LIST_ERROR = 'WALLET_LIST_ERROR'


export const WALLET_LIST_TRANSACTIONS_REQUEST = 'WALLET_LIST_TRANSACTIONS_REQUEST'
export const WALLET_LIST_TRANSACTIONS_SUCCESS = 'WALLET_LIST_TRANSACTIONS_SUCCESS'
export const WALLET_LIST_TRANSACTIONS_ERROR = 'WALLET_LIST_TRANSACTIONS_ERROR'
