export const WALLET_LIST_REQUEST = 'WALLET_LIST_REQUEST'
export const WALLET_LIST_SUCCESS = 'WALLET_LIST_SUCCESS'
export const WALLET_LIST_ERROR = 'WALLET_LIST_ERROR'


export const WALLET_LIST_TRANSACTIONS_REQUEST = 'WALLET_LIST_TRANSACTIONS_REQUEST'
export const WALLET_LIST_TRANSACTIONS_SUCCESS = 'WALLET_LIST_TRANSACTIONS_SUCCESS'
export const WALLET_LIST_TRANSACTIONS_ERROR = 'WALLET_LIST_TRANSACTIONS_ERROR'


export const GET_WALLET_REQUEST = 'GET_WALLET_REQUEST'
export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS'
export const GET_WALLET_ERROR = 'GET_WALLET_ERROR'
